import React from "react";

import Layout from "@/global//layouts/Layout";
import Container from "@/global//layouts/Container";

export default function index({}) {
  return (
    <>
      <Layout contact={[]} title={"xPathEdge | Privacy Policy"}>
        <Container>
          <div className="pt-[16%] md:pt-[32%] lg:pt-[16%] pb-[5%] space-y-8">
            <section className="space-y-4">
              <h2 className="text-4xl font-semibold ">Privacy Policy</h2>

              <p>
                XPATHEDGE (“we,” “our,” or “us”) is committed to protecting your
                privacy. This Privacy Policy explains how your personal
                information is collected, used, and disclosed by XPATHEDGE.
              </p>
              <p>
                This Privacy Policy applies to our website, and its associated
                subdomains (collectively, our “Service”) alongside our
                application, XPATHEDGE. By accessing or using our Service, you
                signify that you have read, understood, and agree to our
                collection, storage, use, and disclosure of your personal
                information as described in this Privacy Policy and our Terms of
                Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold ">
                Definitions and Key Terms
              </h2>
              <p>
                To help explain things as clearly as possible in this Privacy
                Policy, every time any of these terms are referenced, they are
                strictly defined as:
              </p>
              <ul className="list-disc list-inside space-y-2">
                <li>
                  <strong>Cookie:</strong> Small data generated by a website and
                  stored in your browser to identify you and remember
                  preferences or login info.
                </li>
                <li>
                  <strong>Company:</strong> Refers to XPATHEDGE, (110 W Randol
                  Mill Rd Suite 230 Arlington, TX 76011), responsible for your
                  information under this policy.
                </li>
                <li>
                  <strong>Country:</strong> The United States, where XPATHEDGE
                  is based.
                </li>
                <li>
                  <strong>Customer:</strong> A person, company, or organization
                  that signs up to use XPATHEDGE’s services.
                </li>
                <li>
                  <strong>Device:</strong> Any internet-connected device like a
                  phone, tablet, or computer used to access XPATHEDGE.
                </li>
                <li>
                  <strong>IP address:</strong> A number assigned to each device
                  connected to the Internet, often revealing the geographic
                  origin of the connection.
                </li>
                <li>
                  <strong>Personnel:</strong> Individuals employed or contracted
                  by XPATHEDGE.
                </li>
                <li>
                  <strong>Personal Data:</strong> Information that can identify
                  a person, directly or indirectly.
                </li>
                <li>
                  <strong>Service:</strong> The service provided by XPATHEDGE as
                  outlined in relevant terms or on our platform.
                </li>
                <li>
                  <strong>Third-party service:</strong> Advertisers, partners,
                  and others who help us deliver content or services.
                </li>
                <li>
                  <strong>Website:</strong>{" "}
                  <a
                    href="https://www.xpathedge.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 underline"
                  >
                    www.xpathedge.com
                  </a>
                </li>
                <li>
                  <strong>You:</strong> Any person or entity registered with
                  XPATHEDGE to use the Services.
                </li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold ">
                What Information Do We Collect?
              </h2>
              <p>
                We collect information when you visit our site, register, place
                an order, subscribe to a newsletter, respond to surveys, or fill
                out forms.
              </p>
              <ul className="list-disc list-inside space-y-2">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold ">
                When Does XPATHEDGE Use End User Information from Third Parties?
              </h2>
              <p>
                XPATHEDGE collects End User Data necessary to provide services
                to our customers. End users may also voluntarily provide
                information made available on social media platforms. If you do
                so, we may collect publicly available information. You can
                control this via the privacy settings of your social media
                accounts.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold ">
                When Does XPATHEDGE Use Customer Information from Third Parties?
              </h2>
              <p>
                We receive some information from third parties when you interact
                with us. For example, when you submit your email to express
                interest in our service, we may receive data from fraud
                detection services. We may also collect publicly available data
                from social platforms. Again, privacy settings on those
                platforms allow you to manage this visibility.
              </p>
            </section>
          </div>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">
              Do We Share the Information We Collect with Third Parties?
            </h2>
            <p>
              We may share the information that we collect, both personal and
              non-personal, with third parties such as advertisers, contest
              sponsors, promotional and marketing partners, and others who
              provide our content or whose products or services we think may
              interest you. We may also share it with our current and future
              affiliated companies and business partners. In the event of a
              merger, asset sale, or other business reorganization, we may also
              share or transfer your personal and non-personal information to
              our successors-in-interest.
            </p>
            <p>
              We may engage trusted third party service providers to perform
              services on our behalf—such as hosting, email management,
              marketing, credit card processing, and customer service. We will
              likely share your personal and some non-personal information with
              these providers to enable them to deliver their services to us and
              you.
            </p>
            <p>
              Portions of our log file data, including IP addresses, may be
              shared with third parties like web analytics partners, developers,
              and ad networks for analytics purposes. These may be used to
              estimate location, connection speed, or device type. Such partners
              may aggregate and analyze this data for auditing, reporting, and
              marketing use.
            </p>
            <p>
              We may also disclose your information to government or law
              enforcement, or to private parties, if we believe it is necessary
              to respond to legal processes, protect rights, ensure safety,
              prevent illegal activity, or comply with laws and regulations.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              Where and When Is Information Collected from Customers and End
              Users?
            </h2>
            <p>
              XPATHEDGE collects personal information that you submit to us
              directly. We may also receive personal data about you from third
              parties, as described above.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              How Do We Use The Information We Collect?
            </h2>
            <p>
              Any of the information we collect from you may be used in one of
              the following ways:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>To personalize your experience</li>
              <li>To improve our website and services</li>
              <li>To enhance customer service and support</li>
              <li>To process transactions</li>
              <li>
                To administer contests, promotions, surveys, or other features
              </li>
              <li>To send periodic emails</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              How Do We Use Your Email Address?
            </h2>
            <p>
              By submitting your email on this website, you agree to receive
              communication from us. You may unsubscribe at any time by clicking
              the opt-out link included in our emails. We only send emails to
              those who have opted in, and we don’t send spam. Your email may
              also be used for audience targeting in advertising (e.g.,
              Facebook). If you provide your email through another method, we
              may use it as described throughout this policy.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              How Long Do We Keep Your Information?
            </h2>
            <p>
              We retain your information only as long as necessary to provide
              our services and fulfill the purposes in this policy. When no
              longer needed, we delete or anonymize the data unless required by
              law to retain it.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              How Do We Protect Your Information?
            </h2>
            <p>
              We use various security measures to protect your personal data.
              Sensitive information is encrypted via SSL and stored securely
              with limited access. However, no system is entirely secure. We
              cannot guarantee the absolute safety of your information.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              Could My Information Be Transferred to Other Countries?
            </h2>
            <p>
              XPATHEDGE is based in the United States, and your information may
              be transferred globally to our teams or partners. By using our
              services, you consent to this transfer and storage even in
              jurisdictions without equivalent data protection laws.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              Is the Information Collected Through the XPATHEDGE Service Secure?
            </h2>
            <p>
              We take strong precautions to safeguard your information, but no
              method is 100% secure. Despite our efforts, we cannot guarantee
              complete protection. If the law imposes specific standards, our
              obligations will be measured by the standard of intentional
              misconduct.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">
              Can I Update or Correct My Information?
            </h2>
            <p>
              The rights you have to update or correct your information depend
              on your relationship with XPATHEDGE. Personnel may update their
              details according to internal company policies.
            </p>
            <p>
              Customers may request to restrict certain uses or disclosures of
              their personally identifiable information. You may contact us to
              (1) update or correct your information, (2) change communication
              preferences, or (3) delete your account and data, subject to
              verification and technical limitations. These changes won’t affect
              previously shared data with third parties.
            </p>
            <p>
              Please note: it's not technically possible to remove every record.
              While your active records will be modified, backups may still
              contain immutable copies.
            </p>
            <p>
              If you are an end user, please contact the organization you're a
              customer of for updates or deletions.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Personnel</h2>
            <p>
              If you are a worker or applicant, we collect the information you
              voluntarily provide for HR purposes, such as benefits
              administration and applicant screening. You may contact us to
              update or review your records, and we will apply updates as
              appropriate within our systems.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Sale of Business</h2>
            <p>
              In the event of a sale, merger, or reorganization of XPATHEDGE or
              its affiliates, we may transfer your information to the acquiring
              party, provided they agree to uphold this Privacy Policy.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Affiliates</h2>
            <p>
              We may share your information with Corporate Affiliates (entities
              under common control with XPATHEDGE). These entities are required
              to treat your information in accordance with this Privacy Policy.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Governing Law</h2>
            <p>
              This Privacy Policy is governed by the laws of the United States.
              By using our services, you consent to jurisdiction in the United
              States and agree to resolve any disputes under these laws, unless
              otherwise governed by Privacy Shield or other frameworks.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Your Consent</h2>
            <p>
              By using XPATHEDGE, registering an account, or making a purchase,
              you consent to this Privacy Policy and its terms. Continued use of
              our services after updates signifies your acceptance of those
              changes.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Links to Other Websites</h2>
            <p>
              This Privacy Policy applies only to our Services. We are not
              responsible for the practices of other websites linked to or from
              our platform. You should review their respective privacy policies
              and terms before engaging with them.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold ">Cookies</h2>
            <p>
              XPATHEDGE uses cookies to enhance website functionality. These
              small data files help us remember your visit preferences, though
              they are not essential. Disabling cookies may impact website
              features. We do not store personally identifiable information in
              cookies.
            </p>
          </section>

          <section className="space-y-8">
            <div>
              <h2 className="text-xl font-semibold">
                Blocking and Disabling Cookies and Similar Technologies
              </h2>
              <p>
                Wherever you're located you may also set your browser to block
                cookies and similar technologies, but this action may block our
                essential cookies and prevent our website from functioning
                properly, and you may not be able to fully utilize all of its
                features and services. You should also be aware that you may
                lose some saved information (e.g., saved login details, site
                preferences) if you block cookies. Different browsers offer
                different controls. Disabling a cookie or category of cookie
                does not delete the cookie from your browser—you will need to
                delete it manually. Refer to your browser's help menu for more
                information.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">Remarketing Services</h2>
              <p>
                We use remarketing services. In digital marketing, remarketing
                (or retargeting) is the practice of serving ads to people who
                have already visited your website. It enables your company to
                “follow” people around the internet by showing ads on the
                platforms and websites they use most.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">Kids' Privacy</h2>
              <p>
                We do not address anyone under the age of 13. We do not
                knowingly collect personally identifiable information from
                children under 13. If you are a parent or guardian and you
                become aware that your child has provided us with personal data,
                please contact us. If we discover that we have collected
                personal data from a child under 13 without parental consent, we
                will delete that information.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">
                Changes To Our Privacy Policy
              </h2>
              <p>
                We may modify our Service and policies and may update this
                Privacy Policy to reflect those changes. We will notify you of
                changes (for example, via the Service) before they take effect.
                Continued use of the Service after any changes to this Privacy
                Policy indicates your acceptance. If you do not agree, you may
                delete your account.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">Third-Party Services</h2>
              <p>
                We may include third-party content or links to third-party
                websites or services. XPATHEDGE is not responsible for any
                Third-Party Services, including their content, accuracy, or data
                practices. Use of these services is at your own risk and subject
                to their terms and policies.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">Facebook Pixel</h2>
              <p>
                Facebook Pixel is an analytics tool that helps us measure ad
                effectiveness by understanding user actions on our site. It may
                collect data from your device and is governed by Facebook's own
                Privacy Policy.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">
                General Data Protection Regulation (GDPR)
              </h2>
              <p>
                If you are located in the European Economic Area (EEA), we
                explain how and why we collect data under GDPR. GDPR regulates
                how we protect and use EU residents' personal data.
              </p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>
                  Personal data must be processed fairly, legally, and
                  transparently.
                </li>
                <li>
                  It must be used only for specified, legitimate purposes.
                </li>
                <li>It must be retained only as long as necessary.</li>
                <li>
                  Individuals have the right to access, correct, delete, or
                  transfer their data.
                </li>
              </ul>
              <p>
                We process/store personal data with fully vetted, DPA-compliant
                vendors. We retain conversation and personal data for up to 6
                years unless your account is deleted, in which case data is
                removed within 60 days.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">
                California Residents (CCPA)
              </h2>
              <p>
                If you are a California resident, you have the following rights
                under the California Consumer Privacy Act (CCPA):
              </p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>
                  Right to know and access what personal data we collect and how
                  we use it.
                </li>
                <li>
                  Right to equal service regardless of exercising your privacy
                  rights.
                </li>
                <li>Right to delete your personal data.</li>
                <li>
                  Right to request that your personal data not be sold (note: we
                  do not sell your data).
                </li>
              </ul>
              <p>
                We will respond to verified requests within one month. To
                exercise these rights, please contact us.
              </p>
            </div>
          </section>

          <section className="space-y-8 pb-8">
            <div>
              <h2 className="text-xl font-semibold">
                California Online Privacy Protection Act (CalOPPA)
              </h2>
              <p>
                CalOPPA requires us to disclose the categories of Personal
                Information we collect and how we use it, the sources from which
                we collect this information, and the third parties with whom we
                share it—as explained above.
              </p>
              <p>CalOPPA users have the following rights:</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>
                  <strong>Right to Know and Access:</strong> You may submit a
                  verifiable request regarding: (1) categories of Personal
                  Information we collect, use, or share; (2) purposes for which
                  we collect or use it; (3) sources from which we collect it;
                  and (4) specific pieces of data we’ve collected about you.
                </li>
                <li>
                  <strong>Right to Equal Service:</strong> We will not
                  discriminate against you for exercising your privacy rights.
                </li>
                <li>
                  <strong>Right to Delete:</strong> You may request deletion of
                  your personal data and account.
                </li>
                <li>
                  <strong>Right to Opt-Out:</strong> You may request that your
                  personal data not be sold. Note: We do not sell personal data.
                </li>
              </ul>
              <p>
                We will respond to your request within one month. If you wish to
                exercise your rights, please contact us using the information
                below.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold">Contact Us</h2>
              <p>Don't hesitate to reach out if you have any questions.</p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>
                  <strong>Via Email:</strong>{" "}
                  <a
                    href="mailto:hello@xpathedge.com"
                    className="text-blue-600 hover:underline"
                  >
                    hello@xpathedge.com
                  </a>
                </li>
                <li>
                  <strong>Via Phone Number:</strong>{" "}
                  <a
                    href="tel:+14699184632"
                    className="text-blue-600 hover:underline"
                  >
                    +1 (469) 918-4632
                  </a>
                </li>
                <li>
                  <strong>Via this Link:</strong>{" "}
                  <a
                    href="https://www.xpathedge.com/contact"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    https://www.xpathedge.com/contact
                  </a>
                </li>
              </ul>
            </div>
          </section>
        </Container>
      </Layout>
    </>
  );
}
